dictionary = {
    "ability": "The skill or power to do something.",
    "absorb": "To take in a substance or idea fully.",
    "accept": "To agree to take something or approve of it.",
    "accident": "An unexpected event that causes harm or damage.",
    "accompany": "To go somewhere with another person.",
    "achieve": "To successfully reach a goal or complete a task.",
    "active": "Doing things and moving around; energetic.",
    "actual": "Real or existing, not imagined.",
    "adapt": "To change something so it works better in a new situation.",
    "add": "To combine numbers or items to increase the total.",
    "address": "The details of where someone lives or a speech given to people.",
    "adjust": "To change something slightly to make it better.",
    "admire": "To respect or look up to someone.",
    "admit": "To agree that something is true.",
    "adult": "A fully grown person.",
    "advance": "To move forward or make progress.",
    "advice": "Helpful suggestions about what someone should do.",
    "affect": "To cause a change in something.",
    "afford": "To have enough money or resources to do something.",
    "afraid": "Feeling fear or worry.",
    "afterwards": "At a later time; after something else.",
    "agency": "A business or organization that provides a service.",
    "agree": "To have the same opinion as someone else.",
    "ahead": "In front or in the future.",
    "aid": "Help or support given to someone.",
    "aim": "A goal or purpose someone wants to achieve.",
    "air": "The mixture of gases we breathe.",
    "alarm": "A warning sound or signal.",
    "album": "A collection of songs or photographs.",
    "alert": "Quick to notice things; aware.",
    "allow": "To give permission for something to happen.",
    "almost": "Very nearly, but not completely.",
    "alone": "Without other people.",
    "alphabet": "The set of letters used in a language.",
    "already": "Before now or earlier than expected.",
    "also": "In addition; too.",
    "alter": "To change something slightly.",
    "amaze": "To surprise someone greatly.",
    "amount": "The quantity of something.",
    "amuse": "To make someone laugh or smile.",
    "analysis": "Careful study of something to understand it.",
    "ancient": "Very old; from a long time ago.",
    "anger": "A strong feeling of annoyance or displeasure.",
    "animal": "A living creature that moves and responds to its environment.",
    "announce": "To tell people something officially.",
    "annual": "Happening once every year.",
    "answer": "A reply to a question.",
    "anxiety": "A feeling of worry or nervousness.",
    "anyway": "In spite of something; regardless.",
    "apart": "Separated by distance or time.",
    "apology": "A statement saying sorry for something.",
    "appear": "To become visible or seem to exist.",
    "apply": "To make a formal request or put something into use.",
    "appoint": "To choose someone for a job or role.",
    "approach": "To come closer to something.",
    "approve": "To agree that something is acceptable.",
    "argue": "To disagree and give reasons for your opinion.",
    "arise": "To come into being or appear.",
    "arrange": "To organize or plan something.",
    "arrival": "The act of coming to a place.",
    "article": "A piece of writing in a newspaper or magazine.",
    "artist": "A person who creates art.",
    "ashamed": "Feeling embarrassed or guilty.",
    "aside": "To one side.",
    "ask": "To request information or help.",
    "aspect": "A particular part or feature of something.",
    "assist": "To help someone.",
    "associate": "To link ideas or people together.",
    "assume": "To believe something is true without proof.",
    "astonish": "To surprise someone greatly.",
    "attach": "To join or fasten something.",
    "attempt": "To try to do something difficult.",
    "attend": "To be present at an event.",
    "attention": "Focused awareness on something.",
    "attitude": "A way of thinking or feeling.",
    "attract": "To pull something toward you or gain interest.",
    "audience": "People watching or listening to something.",
    "author": "A person who writes books or stories.",
    "available": "Ready to be used or obtained.",
    "average": "The usual or typical amount.",
    "avoid": "To stay away from something.",
    "awake": "Not sleeping.",
    "award": "A prize given for achievement.",
    "aware": "Knowing about something.",
    "awful": "Very bad or unpleasant.",
    "baby": "A very young child.",
    "background": "The part behind the main subject or someone's history.",
    "balance": "A state of stability or equal weight.",
    "band": "A group of musicians.",
    "bank": "A place that keeps and manages money.",
    "barrier": "Something that blocks movement or progress.",
    "base": "The bottom or foundation of something.",
    "basic": "Simple or essential.",
    "battle": "A fight between opposing forces.",
    "beach": "A sandy or pebbly shore beside water.",
    "bear": "A large animal OR to carry something.",
    "beat": "To hit repeatedly or defeat someone.",
    "beautiful": "Very pleasing to look at.",
    "because": "For the reason that something happened.",
    "become": "To begin to be something.",
    "before": "Earlier than something else.",
    "begin": "To start doing something.",
    "behave": "To act in a particular way, especially politely.",
    "belief": "Something accepted as true.",
    "belong": "To be owned by someone or be part of a group.",
    "benefit": "A helpful or positive result.",
    "beside": "Next to something.",
    "better": "Of higher quality or more desirable.",
    "between": "In the space separating two things.",
    "beyond": "Further away than something.",
    "bitter": "Having a sharp, unpleasant taste or feeling.",
    "blank": "Empty or without writing.",
    "blind": "Unable to see.",
    "block": "A solid piece of material or to stop movement.",
    "blood": "The red liquid that flows through the body.",
    "blow": "To move air or to strike with force.",
    "board": "A flat piece of wood or a group of people in charge.",
    "boast": "To talk proudly about achievements.",
    "body": "The physical structure of a person or animal.",
    "bold": "Brave or confident.",
    "bomb": "An explosive device.",
    "bond": "A strong connection between people or things.",
    "bone": "The hard structure inside the body.",
    "book": "A written work printed on pages.",
    "border": "A line separating two areas.",
    "borrow": "To take something temporarily and return it later.",
    "bother": "To annoy or worry someone.",
    "bottle": "A container for liquids.",
    "bottom": "The lowest part of something.",
    "brain": "The organ that controls thought and movement.",
    "branch": "A part of a tree that grows from the trunk.",
    "brave": "Showing courage.",
    "bread": "A food made from flour and baked.",
    "break": "To separate into pieces or stop doing something.",
    "breath": "Air taken in or out of the lungs.",
    "bridge": "A structure built to cross over obstacles.",
    "brief": "Short in time or length.",
    "bright": "Giving a lot of light or intelligent.",
    "bring": "To carry something to a place.",
    "broadcast": "To send out information by radio or TV.",
    "brother": "A male sibling.",
    "budget": "A plan for how money will be spent.",
    "build": "To construct something.",
    "bullet": "A small metal object fired from a gun.",
    "bundle": "A group of things tied together.",
    "burn": "To be on fire or damage with heat.",
    "burst": "To break open suddenly.",
    "business": "The activity of buying and selling goods.",
    "busy": "Having many things to do.",
    "cabin": "A small wooden house.",
    "calculate": "To work out a number or amount.",
    "calm": "Quiet and peaceful.",
    "camera": "A device used to take photos or videos.",
    "camp": "A place where people stay in tents.",
    "cancel": "To stop something from happening.",
    "cancer": "A serious disease involving abnormal cell growth.",
    "capable": "Able to do something.",
    "capital": "A city where a government is based.",
    "capture": "To catch or take control of something.",
    "careful": "Taking care to avoid mistakes or harm.",
    "carriage": "A vehicle pulled by horses.",
    "carry": "To hold and move something.",
    "cartoon": "A drawing or animated film.",
    "case": "A situation or a container.",
    "castle": "A large fortified building.",
    "casual": "Relaxed and informal.",
    "cause": "Something that brings about an effect.",
    "ceiling": "The upper inside surface of a room.",
    "celebrate": "To mark an event with joy.",
    "center": "The middle point of something.",
    "century": "A period of one hundred years.",
    "certain": "Sure or confident.",
    "chain": "A series of connected links.",
    "chair": "A seat for one person.",
    "challenge": "A difficult task that tests ability.",
    "chance": "An opportunity or possibility.",
    "change": "To make something different.",
    "chapter": "A section of a book.",
    "character": "The qualities that make a person unique.",
    "charge": "To ask for payment or to rush forward.",
    "charm": "A pleasing quality.",
    "chart": "A diagram showing information.",
    "chase": "To run after something.",
    "cheap": "Low in price.",
    "check": "To examine something.",
    "cheer": "To shout in support or happiness.",
    "chemical": "A substance used in science or industry.",
    "chest": "The front part of the body between neck and stomach.",
    "chief": "The leader of a group.",
    "child": "A young person.",
    "choice": "The act of selecting between options.",
    "choose": "To pick one option.",
    "church": "A building used for Christian worship.",
    "circle": "A round shape.",
    "citizen": "A person who belongs to a country.",
    "city": "A large town.",
    "civil": "Relating to citizens or polite behavior.",
    "claim": "To say something is true without proof.",
    "class": "A group of students or a category of things.",
    "classic": "Well‑known and admired over time.",
    "claw": "A sharp curved nail on an animal.",
    "clay": "A soft earth material used to make pottery.",
    "clean": "Free from dirt.",
    "clear": "Easy to understand or see.",
    "clerk": "A worker who handles records or customers.",
    "clever": "Quick to understand or learn.",
    "cliff": "A steep rock face.",
    "climate": "The usual weather of a region.",
    "climb": "To move upward using hands and feet.",
    "clock": "A device that shows the time.",
    "close": "To shut something or bring things together.",
    "cloth": "Material made from woven fibres.",
    "cloud": "A mass of water droplets floating in the sky.",
    "club": "A group formed for a shared activity.",
    "coach": "A person who trains others or a type of bus.",
    "coast": "Land beside the sea.",
    "coat": "A warm outer piece of clothing.",
    "code": "A system of symbols or rules used to represent information.",
    "collect": "To gather things together.",
    "college": "A place of higher education.",
    "colour": "A property of light seen as red, blue, green, etc.",
    "column": "A tall pillar or a vertical section of text.",
    "combine": "To join things together.",
    "comfort": "A state of physical ease.",
    "command": "An order given by someone in authority.",
    "comment": "A remark expressing an opinion.",
    "commercial": "Related to business or trade.",
    "commit": "To carry out an action or promise.",
    "committee": "A group chosen to make decisions.",
    "common": "Shared by many people.",
    "communicate": "To share information with others.",
    "community": "A group of people living in the same area.",
    "company": "A business or group of people together.",
    "compare": "To examine similarities and differences.",
    "compete": "To try to win against others.",
    "complain": "To express dissatisfaction.",
    "complete": "Finished or whole.",
    "complex": "Made of many connected parts.",
    "compose": "To create music or writing.",
    "computer": "An electronic device that processes information.",
    "concentrate": "To focus attention on something.",
    "concept": "An idea or general notion.",
    "concern": "A feeling of worry or interest.",
    "concert": "A musical performance.",
    "conclude": "To reach a final decision.",
    "condition": "The state or quality of something.",
    "conduct": "To lead or guide; also behaviour.",
    "confirm": "To show that something is true.",
    "conflict": "A disagreement or struggle.",
    "confuse": "To make someone unable to understand.",
    "connect": "To join or link things together.",
    "conscious": "Aware of what is happening.",
    "consider": "To think carefully about something.",
    "consist": "To be made up of parts.",
    "constant": "Happening all the time.",
    "construct": "To build something.",
    "contact": "Communication or physical touching.",
    "contain": "To hold something inside.",
    "content": "The information inside something.",
    "contest": "A competition.",
    "continue": "To keep going without stopping.",
    "contract": "A written agreement.",
    "control": "The power to direct or manage.",
    "convenient": "Easy to use or suitable.",
    "conversation": "A spoken exchange between people.",
    "convert": "To change something into a different form.",
    "cook": "To prepare food using heat.",
    "cool": "Slightly cold or fashionable.",
    "copy": "To make something identical.",
    "corner": "The point where two edges meet.",
    "correct": "Free from mistakes.",
    "cost": "The amount of money needed to buy something.",
    "cotton": "A soft fibre used to make cloth.",
    "cough": "A sudden sound made when air leaves the lungs.",
    "council": "A group that makes decisions for a community.",
    "count": "To add numbers or items.",
    "country": "A nation with its own government.",
    "courage": "The ability to face fear.",
    "course": "A path or a series of lessons.",
    "court": "A place where legal cases are decided.",
    "cover": "To place something over another thing.",
    "coward": "Someone who lacks courage.",
    "crash": "A violent collision.",
    "create": "To make something new.",
    "creature": "A living being.",
    "credit": "Recognition or trust in payment.",
    "crew": "A group working together, especially on a ship.",
    "crime": "An act that breaks the law.",
    "crisis": "A time of serious difficulty.",
    "critic": "A person who judges the quality of something.",
    "crop": "Plants grown for food.",
    "cross": "To go from one side to another.",
    "crowd": "A large group of people.",
    "cruel": "Causing pain or suffering.",
    "culture": "The customs and arts of a group.",
    "cupboard": "A storage space with doors.",
    "curious": "Wanting to learn or know more.",
    "current": "Happening now.",
    "curve": "A smooth, rounded shape.",
    "custom": "A traditional practice.",
    "customer": "A person who buys goods or services.",
    "cycle": "A series of events that repeat.",
    "daily": "Happening every day.",
    "damage": "Physical harm that reduces value.",
    "dance": "To move rhythmically to music.",
    "danger": "The possibility of harm.",
    "dare": "To have the courage to do something.",
    "dark": "Without light.",
    "data": "Information collected for use.",
    "date": "A day of the month or a meeting with someone.",
    "daughter": "A female child.",
    "daylight": "Natural light from the sun.",
    "dead": "No longer alive.",
    "deal": "An agreement or arrangement.",
    "dear": "Loved or valued.",
    "death": "The end of life.",
    "debate": "A formal discussion of opposing ideas.",
    "decade": "A period of ten years.",
    "decide": "To make a choice after thinking.",
    "declare": "To announce something clearly and officially.",
    "decorate": "To make something look more attractive.",
    "decrease": "To make something smaller in amount.",
    "deep": "Far down from the top or surface.",
    "defeat": "To win against someone in a contest.",
    "defend": "To protect from harm or attack.",
    "define": "To explain the meaning of a word.",
    "degree": "A unit of measurement or a level of achievement.",
    "delay": "To make something happen later than planned.",
    "deliver": "To bring goods or messages to someone.",
    "demand": "A strong request or need for something.",
    "department": "A section of a larger organization.",
    "depend": "To rely on someone or something.",
    "describe": "To explain what something looks or feels like.",
    "desert": "A dry region with very little rainfall.",
    "design": "A plan showing how something should be made.",
    "desire": "A strong feeling of wanting something.",
    "desk": "A piece of furniture used for working.",
    "detail": "A small part of something larger.",
    "detect": "To discover or notice something.",
    "develop": "To grow or improve over time.",
    "device": "A tool or machine created for a purpose.",
    "diagram": "A simple drawing showing how something works.",
    "dialogue": "A conversation between two or more people.",
    "diamond": "A precious stone that is very hard and clear.",
    "dictionary": "A book that explains the meanings of words.",
    "diet": "The food a person usually eats.",
    "difference": "A way in which things are not the same.",
    "difficult": "Hard to do or understand.",
    "digital": "Using electronic signals or computer technology.",
    "dinner": "The main meal of the day.",
    "direct": "Straight or without stopping; also to guide.",
    "direction": "The course along which something moves.",
    "dirt": "Loose earth or anything unclean.",
    "disagree": "To have a different opinion.",
    "disappear": "To stop being visible.",
    "disaster": "A sudden event causing great damage.",
    "discipline": "Training that teaches self‑control.",
    "discover": "To find something for the first time.",
    "discuss": "To talk about something with others.",
    "disease": "An illness that affects the body or mind.",
    "dish": "A container for food or a type of food.",
    "dismiss": "To send someone away or reject an idea.",
    "display": "To show something clearly.",
    "distance": "The amount of space between two points.",
    "distinct": "Clearly different or separate.",
    "district": "A region within a larger area.",
    "divide": "To separate into parts.",
    "document": "A written record providing information.",
    "domestic": "Related to home or family.",
    "double": "Twice as much.",
    "doubt": "A feeling of uncertainty.",
    "downward": "Moving toward a lower place.",
    "dozen": "A group of twelve.",
    "draft": "A first version of a piece of writing.",
    "drag": "To pull something along the ground.",
    "drama": "A play or exciting event.",
    "draw": "To make a picture using lines.",
    "dream": "Thoughts during sleep or a strong wish.",
    "dress": "A piece of clothing worn by women or girls.",
    "drift": "To move slowly without control.",
    "drink": "A liquid that can be swallowed.",
    "drive": "To operate a vehicle.",
    "drop": "To let something fall.",
    "drown": "To die from being underwater.",
    "drug": "A substance used as medicine or taken illegally.",
    "drum": "A musical instrument played by hitting it.",
    "dry": "Without moisture.",
    "dull": "Not interesting or lacking brightness.",
    "during": "Throughout a period of time.",
    "dust": "Tiny particles of dirt.",
    "duty": "Something you are expected to do.",
    "each": "Every one of a group.",
    "eager": "Wanting very much to do something.",
    "early": "Before the usual time.",
    "earn": "To receive money for work.",
    "earth": "The planet we live on.",
    "earthquake": "A sudden shaking of the ground.",
    "easily": "Without difficulty.",
    "east": "The direction where the sun rises.",
    "easy": "Not difficult.",
    "echo": "A repeated sound caused by reflection.",
    "economy": "The system of producing and using goods.",
    "edge": "The outer border of something.",
    "educate": "To teach someone.",
    "effect": "A change caused by an action.",
    "efficient": "Working well without wasting time or energy.",
    "effort": "Physical or mental energy used to do something.",
    "either": "One of two choices.",
    "elder": "Older in age.",
    "elect": "To choose someone for a position.",
    "electric": "Powered by electricity.",
    "element": "A basic part of something.",
    "elephant": "A very large animal with a trunk.",
    "elevator": "A machine that carries people up and down floors.",
    "else": "In addition to something.",
    "embarrass": "To make someone feel awkward or ashamed.",
    "emerge": "To come out or appear.",
    "emotion": "A strong feeling such as joy or anger.",
    "employ": "To give someone a job.",
    "empty": "Containing nothing.",
    "enable": "To make something possible.",
    "encourage": "To give support or confidence.",
    "endless": "Having no limit or end.",
    "decide": "To make a choice after thinking.",
    "decision": "A choice made after considering options.",
    "declare": "To announce something clearly and officially.",
    "decline": "To become smaller or weaker.",
    "decorate": "To make something look more attractive.",
    "decrease": "To make something smaller in amount.",
    "defeat": "To win against someone in a contest.",
    "defend": "To protect from harm or attack.",
    "define": "To explain the meaning of a word.",
    "definite": "Clear and certain.",
    "delay": "To make something happen later than planned.",
    "deliver": "To bring goods or messages to someone.",
    "demand": "A strong request or need for something.",
    "demonstrate": "To show how something works.",
    "deny": "To say something is not true.",
    "department": "A section of a larger organization.",
    "depend": "To rely on someone or something.",
    "describe": "To explain what something looks or feels like.",
    "deserve": "To be worthy of something.",
    "design": "A plan showing how something should be made.",
    "desire": "A strong feeling of wanting something.",
    "desk": "A piece of furniture used for working.",
    "despite": "Even though something happens.",
    "destroy": "To damage something completely.",
    "detail": "A small part of something larger.",
    "detect": "To discover or notice something.",
    "develop": "To grow or improve over time.",
    "device": "A tool or machine created for a purpose.",
    "diagram": "A simple drawing showing how something works.",
    "dialogue": "A conversation between two or more people.",
    "diamond": "A precious stone that is very hard and clear.",
    "dictionary": "A book that explains the meanings of words.",
    "diet": "The food a person usually eats.",
    "difference": "A way in which things are not the same.",
    "difficult": "Hard to do or understand.",
    "digital": "Using electronic signals or computer technology.",
    "dinner": "The main meal of the day.",
    "direct": "Straight or without stopping; also to guide.",
    "direction": "The course along which something moves.",
    "dirt": "Loose earth or anything unclean.",
    "disagree": "To have a different opinion.",
    "disappear": "To stop being visible.",
    "disaster": "A sudden event causing great damage.",
    "discipline": "Training that teaches self‑control.",
    "discover": "To find something for the first time.",
    "discuss": "To talk about something with others.",
    "disease": "An illness that affects the body or mind.",
    "dish": "A container for food or a type of food.",
    "dismiss": "To send someone away or reject an idea.",
    "display": "To show something clearly.",
    "distance": "The amount of space between two points.",
    "distinct": "Clearly different or separate.",
    "district": "A region within a larger area.",
    "divide": "To separate into parts.",
    "document": "A written record providing information.",
    "domestic": "Related to home or family.",
    "double": "Twice as much.",
    "doubt": "A feeling of uncertainty.",
    "downward": "Moving toward a lower place.",
    "dozen": "A group of twelve.",
    "draft": "A first version of a piece of writing.",
    "drag": "To pull something along the ground.",
    "drama": "A play or exciting event.",
    "draw": "To make a picture using lines.",
    "dream": "Thoughts during sleep or a strong wish.",
    "dress": "A piece of clothing worn by women or girls.",
    "drift": "To move slowly without control.",
    "drink": "A liquid that can be swallowed.",
    "drive": "To operate a vehicle.",
    "drop": "To let something fall.",
    "drown": "To die from being underwater.",
    "drug": "A substance used as medicine or taken illegally.",
    "drum": "A musical instrument played by hitting it.",
    "dry": "Without moisture.",
    "dull": "Not interesting or lacking brightness.",
    "during": "Throughout a period of time.",
    "dust": "Tiny particles of dirt.",
    "duty": "Something you are expected to do.",
    "each": "Every one of a group.",
    "eager": "Wanting very much to do something.",
    "early": "Before the usual time.",
    "earn": "To receive money for work.",
    "earth": "The planet we live on.",
    "earthquake": "A sudden shaking of the ground.",
    "easily": "Without difficulty.",
    "east": "The direction where the sun rises.",
    "easy": "Not difficult.",
    "echo": "A repeated sound caused by reflection.",
    "economy": "The system of producing and using goods.",
    "edge": "The outer border of something.",
    "educate": "To teach someone.",
    "effect": "A change caused by an action.",
    "efficient": "Working well without wasting time or energy.",
    "effort": "Physical or mental energy used to do something.",
    "either": "One of two choices.",
    "elder": "Older in age.",
    "elect": "To choose someone for a position.",
    "electric": "Powered by electricity.",
    "element": "A basic part of something.",
    "elephant": "A very large animal with a trunk.",
    "elevator": "A machine that carries people up and down floors.",
    "else": "In addition to something.",
    "embarrass": "To make someone feel awkward or ashamed.",
    "emerge": "To come out or appear.",
    "emotion": "A strong feeling such as joy or anger.",
    "employ": "To give someone a job.",
    "empty": "Containing nothing.",
    "enable": "To make something possible.",
    "encourage": "To give support or confidence.",
    "endless": "Having no limit or end.",
    "energy": "The power needed to do work or make things move.",
    "engine": "A machine that produces movement or power.",
    "enjoy": "To take pleasure in something.",
    "enormous": "Very large in size.",
    "enough": "As much as needed.",
    "ensure": "To make certain something happens.",
    "enter": "To go into a place.",
    "entire": "Whole or complete.",
    "escape": "To get away from danger or confinement.",
    "especially": "More than usual; particularly.",
    "essay": "A short piece of writing on a topic.",
    "essential": "Very important or necessary.",
    "establish": "To set up or create something.",
    "estimate": "To guess the amount or value of something.",
    "event": "Something that happens, especially something important.",
    "evidence": "Information that shows whether something is true.",
    "exact": "Completely correct and precise.",
    "examine": "To look at something carefully.",
    "example": "Something used to show what a concept means.",
    "excellent": "Very good; of high quality.",
    "exchange": "To give one thing and receive another.",
    "excite": "To make someone feel enthusiastic or eager.",
    "exercise": "Physical activity done to stay healthy.",
    "exist": "To be real or present.",
    "expand": "To become larger or increase.",
    "expect": "To believe something will happen.",
    "expense": "The cost of something.",
    "experience": "Knowledge gained through doing or seeing things.",
    "experiment": "A scientific test to discover something.",
    "expert": "A person with special skill or knowledge.",
    "explain": "To make something clear or easy to understand.",
    "explode": "To burst apart violently.",
    "explore": "To travel or study something to learn more.",
    "express": "To show thoughts or feelings.",
    "extend": "To make something longer or larger.",
    "extra": "More than usual.",
    "extreme": "Very great in degree.",
    "eye": "The organ used for seeing.",
    "face": "The front part of the head.",
    "fact": "Something known to be true.",
    "fail": "To not succeed.",
    "fair": "Reasonable or treating people equally.",
    "faith": "Strong belief or trust.",
    "fall": "To drop down from a higher place.",
    "false": "Not true.",
    "familiar": "Well known or easily recognized.",
    "family": "A group of related people.",
    "famous": "Known by many people.",
    "fantastic": "Extremely good.",
    "far": "A long distance away.",
    "farm": "Land used for growing crops or raising animals.",
    "fashion": "Popular styles of clothing or behavior.",
    "fast": "Moving quickly.",
    "fat": "Having a lot of body weight.",
    "fault": "Responsibility for a mistake.",
    "fear": "A feeling of being afraid.",
    "feature": "An important or noticeable part of something.",
    "feed": "To give food to someone or something.",
    "feel": "To experience an emotion or physical sensation.",
    "female": "A person or animal that can produce offspring.",
    "fence": "A barrier used to enclose an area.",
    "festival": "A celebration or event held for enjoyment.",
    "fetch": "To go and bring something back.",
    "fever": "A high body temperature caused by illness.",
    "few": "A small number.",
    "field": "An open area of land or a subject of study.",
    "fight": "To use force to oppose something.",
    "figure": "A number, shape, or person.",
    "file": "A collection of documents or data.",
    "fill": "To make something full.",
    "film": "A movie or motion picture.",
    "final": "Last in a series.",
    "finance": "The management of money.",
    "find": "To discover something.",
    "fine": "Good quality or a payment for breaking a rule.",
    "finger": "One of the five parts on a hand.",
    "finish": "To complete something.",
    "fire": "Heat and light produced by burning.",
    "firm": "Strong or solid; also a business.",
    "first": "Before all others.",
    "fish": "An animal that lives in water.",
    "fit": "Suitable or in good physical condition.",
    "fix": "To repair something.",
    "flag": "A piece of cloth used as a symbol.",
    "flame": "The bright, hot part of fire.",
    "flash": "A sudden burst of light.",
    "flat": "Smooth and level.",
    "flavour": "The taste of food.",
    "flesh": "The soft tissue of animals or humans.",
    "flight": "The act of flying.",
    "float": "To stay on the surface of water.",
    "floor": "The surface you walk on inside a building.",
    "flow": "To move smoothly like water.",
    "flower": "The colourful part of a plant.",
    "fly": "To move through the air.",
    "focus": "To direct attention toward something.",
    "fold": "To bend something over itself.",
    "follow": "To go behind or obey instructions.",
    "food": "Something eaten to stay alive.",
    "fool": "A person who behaves without thinking.",
    "foot": "The part of the body used for standing.",
    "force": "Strength or power used to move something.",
    "forest": "A large area covered with trees.",
    "forget": "To fail to remember.",
    "form": "The shape or structure of something.",
    "fortune": "A large amount of money or luck.",
    "forward": "Toward the front.",
    "found": "To start an organization or discover something.",
    "frame": "A structure that supports something.",
    "free": "Not restricted or costing nothing.",
    "freeze": "To become solid from cold.",
    "fresh": "New or recently made.",
    "friend": "A person you know well and trust.",
    "frighten": "To make someone feel scared.",
    "fruit": "A sweet part of a plant that contains seeds.",
    "fuel": "A substance burned to produce energy.",
    "full": "Containing as much as possible.",
    "function": "The purpose or role of something.",
    "fund": "Money saved or provided for a purpose.",
    "funny": "Causing laughter or amusement.",
    "furniture": "Large movable objects used in a room.",
    "further": "More distant or additional.",
    "future": "The time that has not yet come.",
    "gain": "To get or increase something.",
    "gallery": "A room or building for displaying art.",
    "game": "An activity played for fun or competition.",
    "garage": "A building for storing vehicles.",
    "garden": "An area where plants or flowers are grown.",
    "gas": "A substance that expands to fill any space.",
    "gate": "A movable barrier used to close an opening.",
    "gather": "To bring things together.",
    "general": "Relating to most people or things.",
    "gentle": "Kind and careful.",
    "genuine": "Real and not fake.",
    "gesture": "A movement that expresses meaning.",
    "ghost": "The spirit of a dead person in stories.",
    "giant": "Very large in size.",
    "gift": "Something given to someone without payment.",
    "girl": "A female child.",
    "give": "To hand something to someone.",
    "glad": "Happy or pleased.",
    "glass": "A hard transparent material.",
    "global": "Relating to the whole world.",
    "glove": "A covering for the hand.",
    "goal": "Something a person aims to achieve.",
    "god": "A being worshipped in religion.",
    "gold": "A valuable yellow metal.",
    "good": "Of high quality or morally right.",
    "govern": "To control or manage a country or group.",
    "government": "The group of people who control a country.",
    "grab": "To take something quickly.",
    "grade": "A level of quality or school mark.",
    "grain": "Small hard seeds used as food.",
    "grand": "Large and impressive.",
    "grant": "To give something officially.",
    "grass": "A plant with thin green leaves.",
    "grateful": "Feeling thankful.",
    "gravity": "The force that pulls objects toward Earth.",
    "great": "Very good or large.",
    "green": "The colour of grass.",
    "greet": "To welcome someone.",
    "grey": "A colour between black and white.",
    "ground": "The solid surface of the Earth.",
    "group": "A number of people or things together.",
    "grow": "To increase in size.",
    "growth": "The process of becoming larger.",
    "guard": "A person who protects something.",
    "guess": "To form an idea without full information.",
    "guide": "A person who shows the way.",
    "guilty": "Responsible for doing something wrong.",
    "habit": "A repeated behaviour.",
    "hair": "Thin strands growing from skin.",
    "half": "One of two equal parts.",
    "hall": "A large room or passage.",
    "hammer": "A tool used for hitting nails.",
    "hand": "The part of the body at the end of the arm.",
    "handle": "To deal with something or a part used to hold.",
    "hang": "To suspend something from above.",
    "happen": "To take place or occur.",
    "happy": "Feeling pleasure or joy.",
    "hard": "Solid or difficult.",
    "harm": "Physical or emotional injury.",
    "harvest": "The gathering of crops.",
    "hat": "A covering worn on the head.",
    "hate": "To strongly dislike.",
    "have": "To own or possess.",
    "head": "The top part of the body.",
    "health": "The condition of the body or mind.",
    "hear": "To detect sound.",
    "heart": "The organ that pumps blood.",
    "heat": "Warmth or high temperature.",
    "heavy": "Weighing a lot.",
    "height": "The measurement from bottom to top.",
    "help": "To make something easier for someone.",
    "hero": "A person admired for courage.",
    "hide": "To put something where it cannot be seen.",
    "high": "Tall or far above the ground.",
    "hill": "A raised area of land.",
    "hint": "A small piece of advice.",
    "hire": "To pay someone to do a job.",
    "history": "The study of past events.",
    "hit": "To strike something.",
    "hold": "To keep something in your hands.",
    "hole": "An opening or gap.",
    "holiday": "A day of celebration or rest.",
    "home": "The place where a person lives.",
    "honest": "Truthful and sincere.",
    "honour": "Respect given to someone.",
    "hope": "A feeling of expectation for something good.",
    "horse": "A large animal used for riding.",
    "hospital": "A place where sick people receive treatment.",
    "host": "A person who welcomes guests.",
    "hot": "Having a high temperature.",
    "hour": "A period of sixty minutes.",
    "house": "A building where people live.",
    "human": "A person belonging to the species Homo sapiens.",
    "humble": "Not proud; modest.",
    "humour": "The ability to find things funny.",
    "hundred": "The number 100.",
    "hunt": "To search for animals to catch.",
    "hurry": "To move quickly.",
    "hurt": "To cause pain.",
    "husband": "A married man.",
    "ice": "Frozen water.",
    "idea": "A thought or concept.",
    "ideal": "Perfect or most suitable.",
    "identify": "To recognise or name something.",
    "ignore": "To pay no attention to something.",
    "ill": "Not well; sick.",
    "illegal": "Against the law.",
    "illness": "A condition of being unwell.",
    "illustrate": "To explain using pictures or examples.",
    "image": "A picture or visual representation.",
    "imagine": "To form a picture in your mind.",
    "imitate": "To copy someone or something.",
    "immediate": "Happening right away.",
    "impact": "A strong effect or influence.",
    "important": "Having great meaning or value.",
    "impossible": "Not able to happen or be done.",
    "impress": "To make someone admire something.",
    "improve": "To make something better.",
    "include": "To have something as part of a whole.",
    "income": "Money earned from work or investments.",
    "increase": "To become larger in amount.",
    "indeed": "Used to emphasize a statement.",
    "independent": "Free from control by others.",
    "indicate": "To show or point out.",
    "industry": "Businesses involved in producing goods.",
    "inform": "To give information to someone.",
    "information": "Facts or knowledge provided or learned.",
    "initial": "First or beginning.",
    "injure": "To harm or damage someone.",
    "inner": "Located inside.",
    "innocent": "Not guilty of wrongdoing.",
    "insect": "A small animal with six legs.",
    "insert": "To put something inside something else.",
    "inside": "The inner part of something.",
    "insist": "To demand something firmly.",
    "inspect": "To look at something carefully.",
    "inspire": "To fill someone with the desire to do something.",
    "install": "To put something in place so it works.",
    "instance": "An example of something happening.",
    "instead": "In place of something else.",
    "instrument": "A tool or device used for a purpose.",
    "insult": "To say something rude or hurtful.",
    "insurance": "Protection against loss or damage.",
    "intend": "To plan to do something.",
    "interest": "Curiosity or concern about something.",
    "interfere": "To get involved in something without being wanted.",
    "interior": "The inside part of something.",
    "international": "Relating to more than one country.",
    "internet": "A global computer network.",
    "interrupt": "To stop someone from speaking or doing something.",
    "interview": "A meeting where questions are asked.",
    "introduce": "To present someone or something for the first time.",
    "invent": "To create something new.",
    "invest": "To put money or effort into something for future benefit.",
    "invite": "To ask someone to come somewhere.",
    "involve": "To include or take part in something.",
    "iron": "A strong metal or a tool used to remove wrinkles.",
    "island": "A piece of land surrounded by water.",
    "issue": "A problem or topic for discussion.",
    "item": "A single object or unit.",
    "jacket": "A piece of clothing worn on the upper body.",
    "jail": "A place where criminals are kept.",
    "jam": "A sweet spread made from fruit.",
    "jar": "A glass container with a lid.",
    "jaw": "The lower part of the face that moves when eating.",
    "jealous": "Wanting what someone else has.",
    "join": "To connect or become part of something.",
    "joke": "Something said to make people laugh.",
    "journey": "Travel from one place to another.",
    "joy": "Great happiness.",
    "judge": "A person who decides legal cases.",
    "judgment": "A decision made after thinking.",
    "juice": "Liquid from fruit or vegetables.",
    "jump": "To push off the ground into the air.",
    "jungle": "A dense forest with many plants and animals.",
    "junior": "Younger or lower in rank.",
    "justice": "Fair treatment according to the law.",
    "keen": "Very eager or interested.",
    "keep": "To hold onto something.",
    "key": "A small device used to open locks.",
    "kick": "To strike with the foot.",
    "kid": "A child.",
    "kill": "To cause death.",
    "kind": "Friendly and caring.",
    "king": "A male ruler of a country.",
    "kingdom": "A country ruled by a king or queen.",
    "kiss": "To touch with the lips as a sign of affection.",
    "kitchen": "A room where food is prepared.",
    "knee": "The joint between the thigh and lower leg.",
    "knife": "A tool with a sharp blade.",
    "knock": "To hit a surface to make a sound.",
    "knowledge": "Information and skills gained through learning.",
    "label": "A piece of paper showing information.",
    "labor": "Work, especially physical work.",
    "lack": "To not have enough of something.",
    "lady": "A polite term for a woman.",
    "lake": "A large area of water surrounded by land.",
    "lamp": "A device that gives light.",
    "land": "The solid part of the Earth.",
    "landscape": "The visible features of an area of land.",
    "language": "A system of communication using words.",
    "large": "Big in size.",
    "last": "Coming after all others.",
    "late": "After the expected time.",
    "laugh": "To make a happy sound when amused.",
    "launch": "To send something into motion.",
    "law": "Rules made by a government.",
    "lawyer": "A person trained in law.",
    "lay": "To place something down.",
    "layer": "A thickness of material covering something.",
    "lead": "To guide or be in front.",
    "leader": "A person who directs or inspires others.",
    "leaf": "A flat green part of a plant.",
    "learn": "To gain knowledge or skill.",
    "least": "The smallest amount.",
    "leather": "Material made from animal skin.",
    "leave": "To go away from a place.",
    "lecture": "A talk given to teach something.",
    "left": "The opposite of right.",
    "leg": "A limb used for standing and walking.",
    "legal": "Allowed by law.",
    "lemon": "A sour yellow fruit.",
    "lend": "To give something temporarily.",
    "length": "The measurement of something from end to end.",
    "lesson": "Something taught or learned.",
    "letter": "A written message or a symbol in the alphabet.",
    "level": "A height or stage of progress.",
    "library": "A place where books are kept.",
    "license": "Official permission to do something.",
    "lie": "To rest flat or to say something untrue.",
    "life": "The state of being alive.",
    "lift": "To raise something upward.",
    "light": "Energy that makes things visible.",
    "limit": "A point beyond which something cannot go.",
    "line": "A long narrow mark.",
    "link": "A connection between things.",
    "lion": "A large wild cat.",
    "lip": "The soft edge of the mouth.",
    "liquid": "A substance that flows and is not solid.",
    "list": "A number of items written together.",
    "listen": "To pay attention to sound.",
    "literature": "Written works such as stories and poems.",
    "little": "Small in size or amount.",
    "live": "To be alive or reside somewhere.",
    "load": "To put things onto something.",
    "loan": "Money borrowed and expected to be repaid.",
    "local": "Nearby or relating to a particular area.",
    "lock": "A device used to secure something.",
    "log": "A piece of wood or a record of events.",
    "lonely": "Feeling alone and unhappy.",
    "long": "Measuring a great distance.",
    "look": "To direct your eyes toward something.",
    "loose": "Not tight or firmly fixed.",
    "lord": "A man of high rank.",
    "lose": "To misplace something or fail to win.",
    "loss": "The state of no longer having something.",
    "loud": "Making a strong sound.",
    "love": "A deep feeling of affection.",
    "lovely": "Very attractive or pleasant.",
    "low": "Not high; close to the ground.",
    "loyal": "Faithful and supportive.",
    "luck": "Success or failure caused by chance.",
    "lump": "A small solid mass.",
    "machine": "A device that uses power to perform tasks.",
    "mad": "Very angry or not thinking clearly.",
    "magazine": "A publication containing articles and pictures.",
    "magic": "The use of mysterious or supernatural powers.",
    "magnet": "An object that attracts metal.",
    "mail": "Letters and parcels sent through the post.",
    "main": "Most important.",
    "major": "Large or important.",
    "make": "To create or produce something.",
    "male": "A person or animal that produces sperm.",
    "manage": "To control or organize something.",
    "manner": "A way in which something is done.",
    "many": "A large number.",
    "map": "A drawing showing the features of an area.",
    "march": "To walk in a regular, rhythmic way.",
    "mark": "A visible sign or symbol.",
    "market": "A place where goods are bought and sold.",
    "marriage": "The legal union of two people.",
    "marry": "To join in marriage.",
    "mass": "A large amount of something.",
    "master": "A skilled person or someone in control.",
    "match": "A contest or something that fits well.",
    "material": "A substance used to make things.",
    "matter": "A subject or physical substance.",
    "maximum": "The greatest possible amount.",
    "may": "To be allowed or possibly happen.",
    "meal": "Food eaten at one time.",
    "mean": "To intend or be unkind.",
    "measure": "To find the size or amount of something.",
    "meat": "Animal flesh used as food.",
    "mechanic": "A person who repairs machines.",
    "medicine": "A substance used to treat illness.",
    "medium": "In the middle size or amount.",
    "meet": "To come together with someone.",
    "melt": "To change from solid to liquid.",
    "member": "A person belonging to a group.",
    "memory": "The ability to remember information.",
    "mention": "To refer to something briefly.",
    "menu": "A list of food available in a restaurant.",
    "mess": "A dirty or untidy state.",
    "metal": "A hard, shiny material.",
    "method": "A way of doing something.",
    "middle": "The central point of something.",
    "might": "Possibly or strength.",
    "mild": "Gentle or not strong.",
    "milk": "A white liquid produced by mammals.",
    "mind": "The part of a person that thinks.",
    "mine": "Belonging to me or a place where minerals are dug.",
    "minimum": "The smallest possible amount.",
    "minister": "A government official or religious leader.",
    "minor": "Less important or under legal age.",
    "minute": "A unit of time equal to sixty seconds.",
    "mirror": "A surface that reflects images.",
    "miss": "To fail to hit or to feel the absence of someone.",
    "mission": "A task someone is sent to complete.",
    "mistake": "An incorrect action or decision.",
    "mix": "To combine things together.",
    "mixture": "A combination of different substances.",
    "mobile": "Able to move or relating to phones.",
    "model": "A representation or example of something.",
    "modern": "Relating to the present time.",
    "moment": "A very short period of time.",
    "money": "A medium used to buy goods and services.",
    "monitor": "A screen or device used to check something.",
    "month": "A unit of time based on the calendar.",
    "mood": "A temporary feeling.",
    "moon": "The natural satellite of Earth.",
    "moral": "Relating to right and wrong.",
    "more": "A greater amount.",
    "morning": "The early part of the day.",
    "motion": "Movement from one place to another.",
    "motor": "A machine that produces movement.",
    "mountain": "A large natural elevation of land.",
    "mouse": "A small rodent or a computer device.",
    "mouth": "The opening through which food enters.",
    "move": "To change position.",
    "movie": "A film shown on screen.",
    "movement": "The act of changing position.",
    "movie": "A film shown on a screen.",
    "much": "A large amount.",
    "mud": "Wet, soft earth.",
    "multiple": "Having many parts or elements.",
    "murder": "The unlawful killing of a person.",
    "muscle": "Tissue in the body that helps movement.",
    "museum": "A place where objects of interest are displayed.",
    "music": "Sounds arranged to be pleasant or expressive.",
    "must": "Something that is necessary.",
    "mystery": "Something difficult to understand or explain.",
    "nail": "A thin metal pin or the hard tip of a finger.",
    "name": "A word used to identify someone or something.",
    "narrow": "Not wide.",
    "nation": "A country with its own government.",
    "native": "Belonging to a place by birth.",
    "natural": "Existing in nature, not made by humans.",
    "nature": "The physical world including plants and animals.",
    "near": "Close in distance.",
    "nearly": "Almost but not completely.",
    "neat": "Clean and tidy.",
    "necessary": "Needed or required.",
    "neck": "The part of the body between head and shoulders.",
    "need": "Something required for survival or comfort.",
    "negative": "Showing disagreement or absence.",
    "neighbour": "A person living nearby.",
    "neither": "Not one nor the other.",
    "nervous": "Worried or anxious.",
    "nest": "A structure built by birds for eggs.",
    "net": "A mesh used for catching things.",
    "network": "A group of connected people or systems.",
    "never": "At no time.",
    "new": "Recently made or created.",
    "news": "Information about recent events.",
    "next": "Immediately following.",
    "nice": "Pleasant or kind.",
    "night": "The time when the sun is not visible.",
    "nine": "The number 9.",
    "nobody": "No person.",
    "noise": "Unwanted or unpleasant sound.",
    "none": "Not any.",
    "normal": "Usual or expected.",
    "north": "One of the four main directions.",
    "nose": "The part of the face used for smelling.",
    "note": "A short written message.",
    "nothing": "Not anything.",
    "notice": "To become aware of something.",
    "noun": "A word that names a person, place, or thing.",
    "novel": "A long written story.",
    "now": "At the present time.",
    "nuclear": "Relating to atomic energy.",
    "number": "A symbol used for counting.",
    "nurse": "A person trained to care for the sick.",
    "object": "A thing that can be seen or touched.",
    "observe": "To watch something carefully.",
    "obvious": "Easy to see or understand.",
    "occasion": "A particular time or event.",
    "occupy": "To live in or take up space.",
    "occur": "To happen.",
    "ocean": "A large body of salt water.",
    "odd": "Strange or unusual.",
    "off": "Not operating or away from something.",
    "offer": "To present something for acceptance.",
    "office": "A place where people work at desks.",
    "officer": "A person with authority in an organization.",
    "official": "Approved by authority.",
    "often": "Many times.",
    "oil": "A thick liquid used for cooking or fuel.",
    "old": "Having lived for a long time.",
    "once": "One time.",
    "one": "The number 1.",
    "only": "No more than.",
    "open": "Not closed.",
    "operate": "To control a machine or system.",
    "opinion": "A personal belief or view.",
    "opportunity": "A chance to do something.",
    "oppose": "To disagree or fight against.",
    "option": "A choice between things.",
    "order": "A request or arrangement.",
    "ordinary": "Normal or usual.",
    "organ": "A part of the body with a specific function.",
    "organization": "A group formed for a purpose.",
    "origin": "The beginning or source of something.",
    "other": "Different from the one mentioned.",
    "ought": "Used to express duty or advice.",
    "our": "Belonging to us.",
    "out": "Away from the inside.",
    "outcome": "The result of an action.",
    "outside": "The outer part of something.",
    "over": "Above or across.",
    "own": "Belonging to oneself.",
    "owner": "A person who possesses something.",
    "pack": "To put things into a container.",
    "page": "One side of a sheet in a book.",
    "pain": "An unpleasant physical feeling.",
    "paint": "A coloured liquid used to cover surfaces.",
    "pair": "Two things that belong together.",
    "palace": "A large, grand home for royalty.",
    "pale": "Light in colour.",
    "pan": "A metal container used for cooking.",
    "paper": "Thin material used for writing.",
    "paragraph": "A section of writing.",
    "parent": "A mother or father.",
    "park": "An outdoor area for recreation.",
    "part": "A piece of something larger.",
    "partner": "Someone who shares in an activity.",
    "party": "A social gathering.",
    "pass": "To move by or succeed in a test.",
    "passage": "A narrow path or section of writing.",
    "past": "A time before now.",
    "path": "A track made for walking.",
    "patient": "Able to wait calmly or a person receiving medical care.",
    "pattern": "A repeated design or arrangement.",
    "pause": "To stop briefly.",
    "pay": "To give money for something.",
    "peace": "A state of calm and no conflict.",
    "peak": "The highest point of something.",
    "pen": "A tool used for writing.",
    "pencil": "A writing tool made of wood and graphite.",
    "people": "Human beings.",
    "percent": "A part out of one hundred.",
    "perfect": "Without any mistakes.",
    "perform": "To carry out an action or entertain.",
    "perhaps": "Possibly.",
    "period": "A length of time.",
    "permit": "To allow something.",
    "person": "A human being.",
    "personal": "Relating to an individual.",
    "persuade": "To convince someone to do something.",
    "position": "The place where something is located.",
    "positive": "Showing approval or having a good effect.",
    "possess": "To own something.",
    "possible": "Able to happen or be done.",
    "post": "Mail sent or a pole standing upright.",
    "pot": "A container used for cooking or storing.",
    "potato": "A round vegetable grown underground.",
    "pour": "To make liquid flow from one place to another.",
    "power": "The ability to control or influence.",
    "practical": "Useful and based on real situations.",
    "practice": "Repeated activity to improve skill.",
    "praise": "To express approval or admiration.",
    "pray": "To speak to a god or spirit.",
    "precise": "Exact and accurate.",
    "predict": "To say what will happen in the future.",
    "prefer": "To like something more than another.",
    "prepare": "To get something ready.",
    "present": "Existing now or a gift.",
    "preserve": "To keep something safe from harm.",
    "press": "To push something firmly.",
    "pressure": "Force applied to something.",
    "pretend": "To act as if something is true when it is not.",
    "pretty": "Attractive or pleasant.",
    "prevent": "To stop something from happening.",
    "price": "The amount of money something costs.",
    "pride": "A feeling of satisfaction in achievements.",
    "primary": "Most important or first in order.",
    "prime": "Of the best quality or main.",
    "principal": "The most important person or thing.",
    "print": "To produce text or images on paper.",
    "priority": "Something considered more important than others.",
    "prison": "A place where criminals are kept.",
    "private": "Not for public use.",
    "prize": "Something given as a reward.",
    "probable": "Likely to happen.",
    "problem": "Something difficult to deal with.",
    "process": "A series of actions to achieve a result.",
    "produce": "To make or create something.",
    "product": "Something made for sale.",
    "profession": "A job requiring special training.",
    "profit": "Money gained after expenses.",
    "program": "A planned event or computer instructions.",
    "progress": "Improvement over time.",
    "project": "A planned piece of work.",
    "promise": "A statement that something will be done.",
    "promote": "To support or encourage something.",
    "proof": "Evidence showing something is true.",
    "proper": "Correct or suitable.",
    "property": "Something owned by someone.",
    "protect": "To keep something safe.",
    "prove": "To show something is true.",
    "provide": "To supply something needed.",
    "public": "Relating to everyone.",
    "publish": "To make information available to others.",
    "pull": "To move something toward yourself.",
    "punish": "To make someone suffer for wrongdoing.",
    "pupil": "A student or the black part of the eye.",
    "purchase": "To buy something.",
    "pure": "Clean and not mixed with anything else.",
    "purpose": "The reason for doing something.",
    "push": "To move something away from yourself.",
    "quality": "How good something is.",
    "quantity": "The amount of something.",
    "quarter": "One of four equal parts.",
    "queen": "A female ruler.",
    "question": "Something asked to get information.",
    "quick": "Fast in movement.",
    "quiet": "Making little or no noise.",
    "quit": "To stop doing something.",
    "quite": "To a certain or complete degree.",
    "quote": "To repeat someone else's words.",
    "race": "A competition of speed or a group of people.",
    "radio": "A device that receives sound signals.",
    "rail": "A metal bar used for support or transport.",
    "rain": "Water falling from clouds.",
    "raise": "To lift something higher.",
    "range": "A variety of things or the distance between limits.",
    "rank": "A position in a group.",
    "rapid": "Happening quickly.",
    "rare": "Not common.",
    "rate": "A measure of speed or frequency.",
    "rather": "More willingly or instead.",
    "reach": "To arrive at a place.",
    "react": "To respond to something.",
    "read": "To look at and understand written words.",
    "ready": "Prepared for something.",
    "real": "Not imaginary.",
    "realise": "To become aware of something.",
    "reason": "A cause or explanation.",
    "recall": "To remember something.",
    "receive": "To get something.",
    "recent": "Happening not long ago.",
    "recipe": "Instructions for preparing food.",
    "recognise": "To identify someone or something.",
    "record": "To store information or a written account.",
    "recover": "To get better after illness.",
    "reduce": "To make something smaller.",
    "refer": "To mention something.",
    "reflect": "To bounce back light or think deeply.",
    "reform": "To improve something by changing it.",
    "refuse": "To say no to something.",
    "regard": "To think of someone in a particular way.",
    "region": "An area of land.",
    "regret": "A feeling of sadness about something done.",
    "regular": "Happening often or following a pattern.",
    "reject": "To refuse to accept.",
    "relate": "To connect two things.",
    "relax": "To rest and become calm.",
    "release": "To let something go.",
    "relevant": "Connected to the subject.",
    "relief": "A feeling of comfort after worry.",
    "religion": "Belief in a god or gods.",
    "remain": "To stay in the same place.",
    "remark": "A spoken comment.",
    "remember": "To keep something in your mind.",
    "remind": "To help someone remember.",
    "remove": "To take something away.",
    "repair": "To fix something broken.",
    "repeat": "To do something again.",
    "replace": "To take the place of something.",
    "reply": "To give an answer.",
    "report": "A written or spoken account of something.",
    "represent": "To stand for or act on behalf of something.",
    "request": "To ask for something politely.",
    "require": "To need something.",
    "rescue": "To save someone from danger.",
    "research": "Careful study to discover new information.",
    "reserve": "To keep something for future use.",
    "resist": "To fight against something.",
    "resource": "Something useful that can be used.",
    "respect": "A feeling of admiration for someone.",
    "respond": "To reply or react.",
    "responsible": "Having a duty to take care of something.",
    "rest": "To relax or stop working.",
    "result": "The outcome of an action.",
    "retain": "To keep something.",
    "retire": "To stop working permanently.",
    "return": "To go back or give something back.",
    "reveal": "To show something that was hidden.",
    "review": "To look over something again.",
    "reward": "Something given for good work.",
    "rhythm": "A regular repeated pattern of sound or movement.",
    "rice": "A small grain used as food.",
    "rich": "Having a lot of money or valuable things.",
    "ride": "To travel on something like a bike or horse.",
    "right": "Correct or the opposite of left.",
    "ring": "A circular band or a sound made by a bell.",
    "rise": "To move upward.",
    "risk": "The chance of something bad happening.",
    "river": "A large natural stream of water.",
    "road": "A path for vehicles.",
    "rob": "To steal from a person or place.",
    "rock": "A hard natural material.",
    "role": "A part played by someone.",
    "roll": "To move by turning over and over.",
    "roof": "The top covering of a building.",
    "room": "A space inside a building.",
    "root": "The part of a plant that grows underground.",
    "rope": "A thick strong cord.",
    "rough": "Not smooth or difficult.",
    "round": "Shaped like a circle.",
    "route": "A path from one place to another.",
    "routine": "A regular way of doing things.",
    "row": "A line of things or to move a boat with oars.",
    "royal": "Relating to a king or queen.",
    "rub": "To move something back and forth on a surface.",
    "rule": "A guideline or instruction.",
    "run": "To move quickly on foot.",
    "rush": "To move quickly or with urgency.",
    "sad": "Feeling unhappy.",
    "safe": "Protected from harm.",
    "sail": "To travel on water using wind power.",
    "salary": "Money paid regularly for work.",
    "sale": "The act of selling something.",
    "salt": "A white substance used to flavour food.",
    "same": "Not different.",
    "sand": "Tiny grains found on beaches.",
    "save": "To keep safe or store for later.",
    "say": "To speak words.",
    "scale": "A device for measuring weight or a series of levels.",
    "scan": "To look over something quickly.",
    "scar": "A mark left after a wound heals.",
    "scene": "A part of a play or a view.",
    "school": "A place where people learn.",
    "science": "The study of the natural world.",
    "score": "Points earned in a game.",
    "scratch": "To scrape something with nails or claws.",
    "screen": "A flat surface for showing images.",
    "screw": "A metal fastener with a spiral thread.",
    "sea": "A large body of salt water.",
    "search": "To look for something.",
    "season": "A period of the year with particular weather.",
    "seat": "A place to sit.",
    "second": "One-sixtieth of a minute or next after first.",
    "secret": "Something kept hidden.",
    "section": "A part of something larger.",
    "secure": "Safe and protected.",
    "see": "To use your eyes.",
    "seed": "The part of a plant that can grow into a new plant.",
    "seek": "To look for something.",
    "seem": "To appear to be.",
    "select": "To choose something.",
    "self": "A person's own identity.",
    "sell": "To give something in exchange for money.",
    "send": "To cause something to go somewhere.",
    "sense": "A feeling or ability to understand.",
    "sentence": "A group of words expressing a complete idea.",
    "separate": "To divide into parts.",
    "serious": "Important or needing careful thought.",
    "serve": "To give food or help someone.",
    "service": "Help or work done for someone.",
    "set": "To put something in a particular place.",
    "settle": "To resolve or make a home somewhere.",
    "seven": "The number 7.",
    "several": "More than two but not many.",
    "severe": "Very serious or strict.",
    "shade": "Darkness caused by blocking light.",
    "shadow": "A dark shape made when light is blocked.",
    "shake": "To move something back and forth quickly.",
    "shall": "Used to express future action.",
    "shape": "The outline of something.",
    "share": "To divide something with others.",
    "sharp": "Having a pointed edge.",
    "she": "A female person.",
    "sheep": "An animal with thick wool.",
    "sheet": "A large piece of cloth or paper.",
    "shelf": "A flat board for storing things.",
    "shell": "A hard outer covering.",
    "shelter": "A place that protects from weather or danger.",
    "shift": "To move something from one place to another.",
    "shine": "To give off light.",
    "ship": "A large boat used for travel on water.",
    "shirt": "A piece of clothing worn on the upper body.",
    "shock": "A sudden feeling of surprise or fear.",
    "shoe": "A covering worn on the foot.",
    "shoot": "To fire a bullet or to grow quickly.",
    "shop": "A place where goods are sold.",
    "shore": "Land along the edge of a sea or lake.",
    "short": "Not long in length or time.",
    "should": "Used to express advice or expectation.",
    "shoulder": "The part of the body between neck and arm.",
    "shout": "To speak very loudly.",
    "show": "To display something.",
    "shrink": "To become smaller.",
    "shut": "To close something.",
    "sick": "Unwell or ill.",
    "side": "A surface or edge of something.",
    "sight": "The ability to see.",
    "sign": "A symbol or gesture that gives information.",
    "signal": "A message sent to communicate.",
    "silence": "Complete absence of sound.",
    "silver": "A shiny grey metal.",
    "simple": "Easy to understand.",
    "since": "From a particular time until now.",
    "sing": "To make musical sounds with the voice.",
    "single": "One only.",
    "sink": "To go down below the surface.",
    "sir": "A polite form of address for a man.",
    "sister": "A female sibling.",
    "sit": "To rest on the lower body.",
    "site": "A place where something is located.",
    "situation": "The set of conditions at a particular time.",
    "size": "How big or small something is.",
    "skill": "The ability to do something well.",
    "skin": "The outer covering of the body.",
    "skirt": "A piece of clothing worn around the waist.",
    "sky": "The space above the Earth.",
    "sleep": "To rest with eyes closed.",
    "slice": "A thin piece cut from something.",
    "slide": "To move smoothly along a surface.",
    "slight": "Small in amount.",
    "slow": "Not fast.",
    "small": "Little in size.",
    "smart": "Intelligent or stylish.",
    "smell": "To sense an odour.",
    "smile": "To show happiness with the mouth.",
    "smoke": "The grey gas produced by burning.",
    "smooth": "Even and without roughness.",
    "snake": "A long, legless reptile.",
    "snow": "Frozen white flakes that fall from the sky.",
    "so": "For that reason or to such a degree.",
    "soap": "A substance used for washing.",
    "social": "Relating to society or people.",
    "society": "A community of people living together.",
    "sock": "A soft covering worn on the foot.",
    "soft": "Easy to press or gentle.",
    "soil": "Earth in which plants grow.",
    "soldier": "A person who serves in the army.",
    "solid": "Firm and not liquid.",
    "solution": "An answer to a problem.",
    "solve": "To find the answer.",
    "some": "An unspecified amount.",
    "someone": "An unknown person.",
    "something": "An unspecified thing.",
    "sometimes": "Occasionally.",
    "somewhere": "In an unknown place.",
    "son": "A male child.",
    "song": "A piece of music with words.",
    "soon": "In a short time.",
    "sorry": "Feeling regret.",
    "sort": "A type or category.",
    "sound": "Something heard.",
    "soup": "A liquid food.",
    "south": "One of the four main directions.",
    "space": "An area that is empty or the universe.",
    "spare": "Extra or not needed.",
    "speak": "To talk.",
    "special": "Different from others in a good way.",
    "speech": "Words spoken to an audience.",
    "speed": "How fast something moves.",
    "spell": "To write or say the letters of a word.",
    "spend": "To use money or time.",
    "spill": "To let liquid fall out accidentally.",
    "spin": "To turn around quickly.",
    "spirit": "A person's inner feelings or a ghost.",
    "spite": "A desire to annoy or hurt.",
    "split": "To divide into parts.",
    "sport": "Physical activity for fun or competition.",
    "spot": "A small mark or a particular place.",
    "spread": "To open out or cover a larger area.",
    "spring": "A season or a coiled metal object.",
    "square": "A shape with four equal sides.",
    "stable": "Firm and not likely to change.",
    "staff": "People who work for an organisation.",
    "stage": "A platform for performances.",
    "stair": "A step in a set of steps.",
    "stamp": "A small piece of paper used for postage.",
    "stand": "To be upright on the feet.",
    "standard": "A level of quality.",
    "star": "A bright object in the sky.",
    "start": "To begin.",
    "state": "A condition or a political region.",
    "station": "A place where transport stops.",
    "stay": "To remain in a place.",
    "steady": "Firm and not shaking.",
    "steam": "Water in gas form.",
    "steel": "A strong metal.",
    "step": "A movement of the foot.",
    "stick": "A thin piece of wood or to attach.",
    "still": "Not moving.",
    "stock": "Goods kept for sale.",
    "stone": "A hard natural material.",
    "stop": "To end movement.",
    "store": "A shop or a place to keep things.",
    "storm": "Violent weather with wind and rain.",
    "story": "A tale of events.",
    "straight": "Not curved.",
    "strange": "Unusual or unfamiliar.",
    "strategy": "A plan to achieve a goal.",
    "stream": "A small flowing river.",
    "street": "A public road in a town.",
    "strength": "The power to do things.",
    "stress": "Pressure or worry.",
    "stretch": "To make something longer.",
    "strike": "To hit something.",
    "string": "Thin cord used for tying.",
    "strip": "A long narrow piece.",
    "strong": "Having great power.",
    "structure": "The way parts are arranged.",
    "struggle": "To try hard despite difficulty.",
    "student": "A person who studies.",
    "study": "To learn about a subject.",
    "stuff": "Things or materials.",
    "stupid": "Not intelligent.",
    "style": "A way of doing something.",
    "subject": "A topic or area of study.",
    "submit": "To hand something in for approval.",
    "substance": "A material with particular properties.",
    "subtract": "To take one number away from another.",
    "succeed": "To achieve a goal.",
    "success": "The achievement of something desired.",
    "such": "Of the type already mentioned.",
    "sudden": "Happening quickly without warning.",
    "suffer": "To experience pain or hardship.",
    "sugar": "A sweet substance used in food.",
    "suggest": "To offer an idea for consideration.",
    "suit": "A set of matching clothes or something appropriate.",
    "summer": "The warmest season of the year.",
    "sun": "The star that gives Earth light and heat.",
    "super": "Very good or excellent.",
    "supply": "To provide something needed.",
    "support": "To help or encourage.",
    "suppose": "To think something is likely.",
    "sure": "Confident or certain.",
    "surface": "The outside layer of something.",
    "surprise": "An unexpected event.",
    "surround": "To be all around something.",
    "survey": "To examine something carefully.",
    "survive": "To continue living despite danger.",
    "suspect": "To believe someone may be guilty.",
    "swear": "To promise strongly or use rude language.",
    "sweep": "To clean by brushing.",
    "sweet": "Tasting like sugar.",
    "swim": "To move through water.",
    "swing": "To move back and forth.",
    "switch": "To change from one thing to another.",
    "symbol": "A sign representing something else.",
    "system": "A set of connected parts working together.",
    "table": "A piece of furniture with a flat top.",
    "tackle": "To deal with a difficult problem.",
    "tail": "The long back part of an animal.",
    "take": "To remove or accept something.",
    "tale": "A story, often imaginative.",
    "talent": "A natural ability.",
    "talk": "To speak with someone.",
    "tall": "Having great height.",
    "tank": "A large container for liquid.",
    "tap": "To touch lightly or a device controlling water.",
    "target": "Something aimed at.",
    "task": "A piece of work to be done.",
    "taste": "The flavour of food.",
    "tax": "Money paid to the government.",
    "tea": "A drink made from dried leaves.",
    "teach": "To help someone learn.",
    "team": "A group working together.",
    "tear": "To rip something or drops from the eye.",
    "technical": "Related to practical skills or machines.",
    "technology": "Tools and machines created using science.",
    "telephone": "A device used for speaking over distance.",
    "television": "A device that shows moving images.",
    "tell": "To give information.",
    "temperature": "How hot or cold something is.",
    "tend": "To be likely to do something.",
    "term": "A period of time or a word used in study.",
    "terrible": "Very bad.",
    "test": "A way to measure knowledge or ability.",
    "text": "Written words.",
    "than": "Used to compare two things.",
    "thank": "To express gratitude.",
    "that": "Used to refer to something mentioned.",
    "theatre": "A place where plays are performed.",
    "their": "Belonging to them.",
    "them": "Referring to people or things already mentioned.",
    "theme": "The main idea of something.",
    "then": "At that time or next.",
    "theory": "An idea explaining something.",
    "there": "In that place.",
    "therefore": "For that reason.",
    "they": "People or things already mentioned.",
    "thick": "Having a large distance between sides.",
    "thin": "Having little distance between sides.",
    "thing": "An object or idea.",
    "think": "To use the mind to form ideas.",
    "third": "Coming after second.",
    "thirst": "A need to drink.",
    "this": "Referring to something close.",
    "thorough": "Done completely and carefully.",
    "those": "Referring to things far away.",
    "though": "Despite the fact.",
    "thought": "An idea formed in the mind.",
    "thousand": "The number 1000.",
    "thread": "A thin strand used for sewing.",
    "threat": "A sign of possible harm.",
    "three": "The number 3.",
    "throat": "The passage from mouth to stomach.",
    "through": "From one side to the other.",
    "throw": "To send something through the air.",
    "thumb": "The short, thick finger.",
    "thunder": "The loud sound after lightning.",
    "ticket": "A piece of paper allowing entry.",
    "tie": "To fasten with a knot.",
    "tight": "Firm and not loose.",
    "till": "Until.",
    "time": "A measure of moments.",
    "tin": "A metal container or a type of metal.",
    "tiny": "Very small.",
    "tip": "A helpful hint or the pointed end.",
    "tire": "To become tired.",
    "title": "The name of a book or film.",
    "to": "Used to show direction or purpose.",
    "today": "The present day.",
    "toe": "One of the five parts of the foot.",
    "together": "With others.",
    "tomorrow": "The day after today.",
    "tone": "The quality of a sound or voice.",
    "tongue": "The muscle in the mouth used for taste and speech.",
    "tonight": "The evening of today.",
    "too": "More than needed or also.",
    "tool": "A device used to do work.",
    "tooth": "A hard part in the mouth used for chewing.",
    "top": "The highest or uppermost part.",
    "topic": "A subject being discussed.",
    "total": "The whole amount.",
    "touch": "To make physical contact.",
    "tough": "Strong or difficult to break.",
    "tour": "A journey to visit places.",
    "toward": "In the direction of.",
    "tower": "A tall narrow building.",
    "town": "A place where people live, smaller than a city.",
    "toy": "An object for children to play with.",
    "track": "A path or route.",
    "trade": "Buying and selling goods.",
    "tradition": "A long‑established custom.",
    "traffic": "Vehicles moving on roads.",
    "train": "A vehicle that runs on rails or to teach someone.",
    "training": "Practice to learn a skill.",
    "transfer": "To move something from one place to another.",
    "transform": "To change completely.",
    "translate": "To change words into another language.",
    "transport": "To carry people or goods.",
    "trap": "A device for catching something.",
    "travel": "To go from one place to another.",
    "treat": "To behave in a certain way toward someone.",
    "treatment": "Medical care or handling of a situation.",
    "tree": "A tall plant with a trunk.",
    "trend": "A general direction of change.",
    "trial": "A test or a legal process.",
    "triangle": "A shape with three sides.",
    "trick": "A clever action meant to deceive or amuse.",
    "trip": "A short journey.",
    "troop": "A group of soldiers.",
    "trouble": "Difficulty or problems.",
    "truck": "A large vehicle for carrying goods.",
    "true": "Correct or factual.",
    "trust": "Belief in someone's reliability.",
    "truth": "Something that is correct.",
    "try": "To attempt something.",
    "tube": "A long hollow object.",
    "tune": "A melody.",
    "turn": "To move in a different direction.",
    "twice": "Two times.",
    "twin": "One of two children born at the same time.",
    "twist": "To turn something into a spiral shape.",
    "type": "A category of things.",
    "typical": "Usual or expected.",
    "ugly": "Unpleasant to look at.",
    "ultimate": "The final or most important.",
    "unable": "Not able to do something.",
    "uncle": "A brother of a parent.",
    "under": "Below something.",
    "understand": "To know the meaning of something.",
    "uniform": "Clothing worn by members of a group.",
    "union": "A group formed for a common purpose.",
    "unique": "One of a kind.",
    "unit": "A single complete thing.",
    "universe": "All space and everything in it.",
    "unknown": "Not known.",
    "unless": "Except if.",
    "unlike": "Different from.",
    "until": "Up to a certain time.",
    "unusual": "Not common.",
    "up": "Toward a higher place.",
    "update": "To make something more current.",
    "upon": "On or immediately after.",
    "upper": "Higher in position.",
    "upset": "Unhappy or disturbed.",
    "urban": "Relating to cities.",
    "urge": "To strongly encourage.",
    "use": "To employ something for a purpose.",
    "useful": "Helpful for achieving something.",
    "usual": "Normal or expected.",
    "vacation": "A period of rest or travel.",
    "valley": "Low land between hills.",
    "valuable": "Worth a lot of money.",
    "value": "The importance or worth of something.",
    "van": "A vehicle used for carrying goods.",
    "variety": "A range of different things.",
    "various": "Different from one another.",
    "vast": "Very large.",
    "vegetable": "A plant used as food.",
    "vehicle": "Something used for transporting people or goods.",
    "version": "A particular form of something.",
    "very": "To a high degree.",
    "vessel": "A container or a ship.",
    "victim": "Someone harmed by an event.",
    "victory": "Success in a contest.",
    "video": "Moving images recorded electronically.",
    "view": "A sight or opinion.",
    "village": "A small community in the countryside.",
    "violence": "Physical force meant to harm.",
    "visit": "To go to see someone or someplace.",
    "voice": "The sound produced when speaking.",
    "volume": "The amount of space something takes or loudness.",
    "vote": "To choose a leader or decision.",
    "voyage": "A long journey, especially by sea.",
    "wage": "Money earned for work.",
    "wait": "To stay in one place until something happens.",
    "wake": "To stop sleeping.",
    "walk": "To move on foot.",
    "wall": "A vertical structure dividing spaces.",
    "want": "To desire something.",
    "war": "Armed conflict between groups.",
    "warm": "Slightly hot.",
    "warn": "To tell someone about danger.",
    "wash": "To clean with water.",
    "waste": "To use something carelessly.",
    "watch": "To look at something carefully.",
    "water": "A clear liquid essential for life.",
    "wave": "A moving ridge on water or a hand gesture.",
    "way": "A method or path.",
    "weak": "Not strong.",
    "wealth": "A large amount of money or possessions.",
    "weapon": "Something used to cause harm.",
    "wear": "To have clothes on.",
    "weather": "Conditions of the atmosphere.",
    "web": "A network or a spider’s silk structure.",
    "wedding": "A ceremony where two people marry.",
    "week": "A period of seven days.",
    "weigh": "To measure weight.",
    "weight": "How heavy something is.",
    "welcome": "To greet someone warmly.",
    "wood": "The hard material that forms the trunk of trees.",
    "wool": "A soft fibre from sheep used to make clothes.",
    "word": "A unit of language with meaning.",
    "work": "Activity done to achieve a purpose.",
    "worker": "A person who performs a job.",
    "world": "The Earth and all its people.",
    "worry": "To feel anxious about something.",
    "worse": "More bad than something else.",
    "worst": "The most bad.",
    "worth": "The value of something.",
    "would": "Used to talk about imagined or future actions.",
    "wound": "An injury to the body.",
    "wrap": "To cover something completely.",
    "write": "To form letters or words.",
    "writer": "A person who writes books or stories.",
    "wrong": "Not correct.",
    "yard": "An outdoor area near a house.",
    "year": "A period of twelve months.",
    "yellow": "A bright colour like the sun.",
    "yes": "A word used to show agreement.",
    "yesterday": "The day before today.",
    "yet": "Up to now or however.",
    "young": "Not old.",
    "youth": "The time of being young.",
    "zone": "An area with particular features.",
    "zoo": "A place where animals are kept for visitors."
}


Name = input("Hello! What's your name? ")
print(f"Hi {Name}")
How = input("How are you? (Good/Bad) ")

if How.lower() == "Good":
    print("Great! Ask me to Define something")
else:
    print("Maybe next time(Check out pygo for more fun projects) Ask me to Define something!")

print("Dictionary Bot is ready. Ask me: Define (word)\n")

while True:
    user_input = input("You: ").lower()

    if user_input == "exit":
        print("Bot: Goodbye!")
        break

    if user_input.startswith("define "):
        word = user_input.replace("define ", "").strip()

        if word in dictionary:
            print("\nDefinition of", word + ":")
            print(dictionary[word], "\n")
        else:
            print("Bot: Sorry, I don't have a definition for that word.\n")
    else:
        print("Please ask like this → Define football\n")